#ifndef CHACHA20_HPP
#define CHACHA20_HPP

#include <cstdint>
#include <array>
#include <vector>
#include <cstring>

// Class to implement the ChaCha20 stream cipher for encryption and decryption
// The ChaCha20 algorithm is a symmetric key cipher that generates a pseudorandom keystream
// The keystream is XORed with the plaintext to produce ciphertext, and vice versa for decryption
class ChaCha20 {
private:
    std::array<uint32_t, 16> state; // Internal state of the ChaCha20 cipher

    // Rotate left operation for 32-bit integers
    static inline uint32_t rotateLeft(uint32_t value, int shift) {
        return (value << shift) | (value >> (32 - shift));
    }

    // The quarter round function is a core operation in the ChaCha20 algorithm
    static inline void quarterRound(uint32_t& a, uint32_t& b, uint32_t& c, uint32_t& d) {
        a += b; d ^= a; d = rotateLeft(d, 16);
        c += d; b ^= c; b = rotateLeft(b, 12);
        a += b; d ^= a; d = rotateLeft(d, 8);
        c += d; b ^= c; b = rotateLeft(b, 7);
    }

    // Helper functions to convert between little-endian byte arrays and uint32_t values
    static inline uint32_t littleEndianToUint32(const uint8_t* bytes) {
        return static_cast<uint32_t>(bytes[0]) |
               (static_cast<uint32_t>(bytes[1]) << 8) |
               (static_cast<uint32_t>(bytes[2]) << 16) |
               (static_cast<uint32_t>(bytes[3]) << 24);
    }

    // Helper function to convert a uint32_t value to a little-endian byte array
    static inline void uint32ToLittleEndian(uint32_t value, uint8_t* bytes) {
        bytes[0] = static_cast<uint8_t>(value & 0xFF);
        bytes[1] = static_cast<uint8_t>((value >> 8) & 0xFF);
        bytes[2] = static_cast<uint8_t>((value >> 16) & 0xFF);
        bytes[3] = static_cast<uint8_t>((value >> 24) & 0xFF);
    }

public:
    // Initialize the ChaCha20 state with the key, nonce, and counter
    void initialize(const std::array<uint8_t, 32>& key, const std::array<uint8_t, 12>& nonce, uint32_t counter) {
        // Initialize the state with the key, nonce, and counter
        state[0] = 0x61707865; // "expa"
        state[1] = 0x3320646e; // "nd 3"
        state[2] = 0x79622d32; // "2-by"
        state[3] = 0x6b206574; // "te k"

        // Load the key into the state
        for (int i = 0; i < 8; ++i) {
            state[4 + i] = littleEndianToUint32(&key[i * 4]);
        }

        state[12] = counter;
        for (int i = 0; i < 3; ++i) {
            state[13 + i] = littleEndianToUint32(&nonce[i * 4]);
        }
    }

    // Generate a 64-byte keystream block based on the current state
    void generateKeystreamBlock(uint8_t* output) {
        std::array<uint32_t, 16> workingState = state;

        // Perform 20 rounds of the ChaCha20 algorithm (10 double rounds)
        for (int i = 0; i < 10; ++i) { // 20 rounds (10 double rounds)
            quarterRound(workingState[0], workingState[4], workingState[8], workingState[12]);
            quarterRound(workingState[1], workingState[5], workingState[9], workingState[13]);
            quarterRound(workingState[2], workingState[6], workingState[10], workingState[14]);
            quarterRound(workingState[3], workingState[7], workingState[11], workingState[15]);

            quarterRound(workingState[0], workingState[5], workingState[10], workingState[15]);
            quarterRound(workingState[1], workingState[6], workingState[11], workingState[12]);
            quarterRound(workingState[2], workingState[7], workingState[8], workingState[13]);
            quarterRound(workingState[3], workingState[4], workingState[9], workingState[14]);
        }

        for (int i = 0; i < 16; ++i) {
            uint32ToLittleEndian(workingState[i] + state[i], &output[i * 4]);
        }

        state[12]++; // Increment the counter for the next block
    }

    // Encrypt the plaintext using the ChaCha20 cipher and produce ciphertext
    // The ciphertext is generated by XORing the plaintext with the keystream
    static void encrypt(const std::array<uint8_t, 32>& key, const std::array<uint8_t, 12>& nonce, uint32_t counter, const std::vector<uint8_t>& plaintext, std::vector<uint8_t>& ciphertext) {
        ChaCha20 chacha;
        chacha.initialize(key, nonce, counter);

        size_t blockCount = (plaintext.size() + 63) / 64; // Number of 64-byte blocks
        ciphertext.resize(plaintext.size());

        // Process each block of plaintext
        for (size_t i = 0; i < blockCount; ++i) {
            uint8_t keystream[64];
            chacha.generateKeystreamBlock(keystream);

            size_t blockSize = (i == blockCount - 1) ? (plaintext.size() % 64) : 64;
            for (size_t j = 0; j < blockSize; ++j) {
                ciphertext[i * 64 + j] = plaintext[i * 64 + j] ^ keystream[j];
            }
        }

        // Handle the case where the last block is exactly 64 bytes
        if (plaintext.size() % 64 == 0 && !plaintext.empty()) {
            // Handle the case where the last block is exactly 64 bytes
            uint8_t keystream[64];
            chacha.generateKeystreamBlock(keystream);
            for (size_t j = 0; j < 64; ++j) {
                ciphertext[blockCount * 64 + j] = keystream[j];
            }
        }
    }

};

#endif // CHACHA20_HPP